// packages/di/react/src/di-context/di.provider.tsx
import {ContainerI} from "@mygoodstack/di-core";
import {type PropsWithChildren, useState} from "react";
import {DIContext} from "./di.context";

export function DIProvider({children, container: initContainer}: PropsWithChildren<{
    container: ContainerI
}>) {
    const [container, setContainer] = useState<ContainerI>(initContainer)
    return (
        <DIContext.Provider value={{container, setContainer}}>
            {children}
        </DIContext.Provider>
    );
}

// packages/di/vue/src/di-context/di.provider.vue
<script lang="ts" setup>
import {ContainerI} from "@mygoodstack/di-core";
import {provide} from 'vue';
import {useState} from "../use-state";
import {diContainerKey} from "./di-container-key";

const props = defineProps<{
  container: ContainerI;
}>();

const [container, setContainer] = useState<ContainerI>(props.container);

provide(diContainerKey, {
  container,
  setContainer
});

</script>

<template>
  <slot/>
</template>
