// examples/vite-react-demo/src/App.tsx
import viteLogo from '/vite.svg'
import './App.css'
import {containerByEnv, useDI, useInstance} from "@mygoodstack/di-react";
import {useState} from 'react'
import reactLogo from './assets/react.svg'
import {UserService} from "./services/user.service";

function App() {
    const [count, setCount] = useState(0)

    const {setContainer} = useDI();
    const userService = useInstance(UserService);

    return (
        <>
            <div>
                <a href="https://vite.dev" target="_blank">
                    <img src={viteLogo} className="logo" alt="Vite logo"/>
                </a>
                <a href="https://react.dev" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo"/>
                </a>
            </div>
            <h1>Vite + React + {userService.getUserName()}</h1>
            <div className="card">
                <button onClick={() => setCount((count) => count + 1)}>
                    count is {count}
                </button>
                <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                </p>
                <button onClick={() => setContainer(() => containerByEnv.development)}>
                    change container to development
                </button>
                <button onClick={() => setContainer(() => containerByEnv.mock)}>
                    change container to mock
                </button>
            </div>
            <p className="read-the-docs">
                Click on the Vite and React logos to learn more
            </p>
        </>
    )
}

export default App

// examples/vite-vue-demo/src/App.vue
<script setup lang="ts">
import {containerByEnv, useDI, useInstance} from "@mygoodstack/di-vue";
import HelloWorld from './components/HelloWorld.vue'
import {UserService} from "./services/user.service";

const {setContainer} = useDI();
const userService = useInstance(UserService);

</script>

<template>
    <div>
      <a href="https://vite.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
  <HelloWorld :msg="`Vite + Vue + ${userService.getUserName()}`" />
    <button @click="setContainer(containerByEnv.development)">
      change container to development
    </button>
    <button @click="setContainer(containerByEnv.mock)">
      change container to mock
    </button>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
